name: Deploy

on: [push]

jobs:  
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        
        - name: multiple command
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_KEY_1 }}
            port: ${{ secrets.PORT }}
            script: |
              cd ~/github-action
              rm -rf image-animated-swapping-with-text-in-middle
              git clone https://github.com/minhaz1217/image-animated-swapping-with-text-in-middle.git
              cd image-animated-swapping-with-text-in-middle
              sudo -S docker image rm ia-image-animated-swapping-with-text-in-middle <<< "${{ secrets.MYSUCCESS }}"
              sudo -S docker rm image-animated-swapping-with-text-in-middle --force
              sudo -S docker build -t ia-image-animated-swapping-with-text-in-middle . <<< "${{ secrets.MYSUCCESS }}"
              sudo -S docker run -dit --name image-animated-swapping-with-text-in-middle --network ${{ secrets.DOCKER_NETWORK }} ia-image-animated-swapping-with-text-in-middle  <<< "${{ secrets.MYSUCCESS }}"
              sudo -S docker ps  <<< "${{ secrets.MYSUCCESS }}"